kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-cluster-viewer-kcafy

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-viewer-kcafy
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-viewer-kcafy
subjects:
- kind: ServiceAccount
  name: account-cluster-viewer-kcafy
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-cluster-viewer-kcafy
  apiGroup: rbac.authorization.k8s.io

error.api.no_namespace_privilege: physicalmachinechaos.chaos-mesh.org is forbidden: User "system:serviceaccount:default:account-cluster-viewer-vqrby" cannot create resource "physicalmachinechaos" in API group "chaos-mesh.org" in the namespace "chaos-testing"